#!/usr/bin/env bash

h5_dir=$1 # directory containing the h5 files after watershed with row-col tile coordinate on WSI
tif_dir=$2 # directory containing the tif files 
npz_dir=$3 # directory containing the output files
id=$4     # patient id
report=${id}_report

if [ -d /usr/local/share/anaconda3 ]; then
    path2anaconda=/usr/local/share/anaconda3
    echo The python executable directory is $path2anaconda
fi
if [ -d /home/garner1/miniconda3 ]; then
    path2anaconda=/home/garner1/miniconda3
    echo The python executable directory is $path2anaconda
fi

mkdir -p ${npz_dir}		# create if it does not exist

[ -d ${h5_dir} ] && [ -d ${tif_dir} ] && [ -d ${npz_dir} ] &&
    parallel "${path2anaconda}/bin/python3.7 pipe1.img2centroid_area_intensity.py ${h5_dir}/{} ${tif_dir}/{.}.tif ${npz_dir}/{.} ${report}" ::: $(cd ${h5_dir}; ls *.h5) &&
    echo Done with pipe1 &&
    ${path2anaconda}/bin/python3.7 pipe2.stitching.py ${npz_dir} 512 ${id} &&
    echo Done with pipe2 &&
    ${path2anaconda}/bin/python3.7 pipe3.graphSegmentation.py ./${id}_data_RC-XY-A-I.npz ${id} &&
    echo Done with pipe3 

