#!/usr/bin/env bash

h5_dir=$1 # directory containing the h5 files after watershed with row-col tile coordinate on WSI
tif_dir=$2 # directory containing the tif files 
npz_dir=$3 # directory containing the output files
id=ID2     # patient id
report=${id}_report

[ -d ${h5_dir} ] && [ -d ${tif_dir} ] && [ -d ${npz_dir} ] &&
    parallel "/usr/local/share/anaconda3/bin/python3.7 pipe1.img2centroid_area_intensity.py ${h5_dir}/{} ${tif_dir}/{.}.tif ${npz_dir}/{.} ${report}" ::: $(cd ${h5_dir}; ls *.h5) &&
    echo Done with pipe1 &&
    /usr/local/share/anaconda3/bin/python3.7 pipe2.stitching.py ${npz_dir} 512 ${id} &&
    echo Done with pipe2 &&
    /usr/local/share/anaconda3/bin/python3.7 pipe3.graphSegmentation.py /home/garner1/Work/dataset/tissue2graph/${id}_data_RC-XY-A-I.npz ${id} &&
    echo Done with pipe3 

