#!/usr/bin/env bash

h5_dir=$1 # directory containing the h5 files after watershed with row-col tile coordinate on WSI
tif_dir=$2 # directory containing the tif files 
npz_dir=$3 # directory containing the output files
id=$4     # patient id
report=${id}_report

if [ -d /usr/local/share/anaconda3 ]; then
    path2anaconda=/usr/local/share/anaconda3
    echo The python executable directory is $path2anaconda
fi
if [ -d /home/garner1/miniconda3 ]; then
    path2anaconda=/home/garner1/miniconda3
    echo The python executable directory is $path2anaconda
fi

mkdir -p ${npz_dir}		# create if it does not exist

[ -d ${h5_dir} ] && [ -d ${tif_dir} ] && [ -d ${npz_dir} ] &&
    # parallel "${path2anaconda}/bin/python3.7 pipe1.img2features.py ${h5_dir}/{} ${tif_dir}/{.}.tif ${npz_dir}/{.} ${report}" ::: $(cd ${h5_dir}; ls *.h5) &&
    # echo Done with pipe1 &&
    # ${path2anaconda}/bin/python3.7 pipe2.stitching.py ${npz_dir} 512 ${id} &&
    # echo Done with pipe2 &&
    # ${path2anaconda}/bin/python3.7 pipe3.makeGraph.py ./${id}_data.npz ${id} &&
    # echo Done with pipe3 &&
    parallel "${path2anaconda}/bin/python3.7 pipe4.walk.py ./npz/${id}_data.npz ./npz/${id}_graph.npz {} 1000 ${id}" ::: area intensity perimeter eccentricity solidity &&
    echo Done with pipe4 &&
    parallel "${path2anaconda}/bin/python3.7 pipe5.drawHeatMap.py ./npy/${id}-{1}-walkhistory.npy ./npz/${id}_data.npz {1} {2} ${id} {3}" ::: area intensity perimeter eccentricity solidity ::: $(seq 100 100 1000) ::: linear percentiles
    echo Done with pipe5



